apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.cfg: |
    events {
      worker_connections 1024;
    }

    http {
      upstream backend {
        server app-1:8080;
        server app-2:8080;
      }

      server {
        location / {
          proxy_pass http://backend;
        }
      }
    }
